import userIcon from "../../assets/images/usersIcon.png";

export const chatsData = [
  {
    pp: userIcon,
    contact: "Coding Spot",
    msg: "Awesome, thank you!",
    time: "1:15 pm",
    unreadMsgs: null,
  },
  {
    pp: userIcon,
    contact: "Tom",
    msg: "Coding Spot is fire! 🔥",
    time: "12:15 pm",
    unreadMsgs: 2,
  },
  {
    pp: userIcon,
    contact: "Girlfriend ❤️",
    msg: "Miss you, call you later!",
    time: "11:11 am",
    unreadMsgs: 4,
  },
  {
    pp: userIcon,
    contact: "Dad",
    msg: "Hey dad, need you asap!!",
    time: "11:04 am",
    unreadMsgs: null,
  },
  {
    pp: userIcon,
    contact: "+00 123 4567890",
    msg: "Who are you???",
    time: "10:58 am",
    unreadMsgs: null,
  },
  {
    pp: userIcon,
    contact: "Coders </>",
    msg: "Help me with this bug!! 😭😭",
    time: "10:50 am",
    unreadMsgs: 23,
  },
  {
    pp: userIcon,
    contact: "Mom",
    msg: "Call me son, love you. ❤️",
    time: "10:35 am",
    unreadMsgs: 2,
  },
  {
    pp: userIcon,
    contact: "Johnny",
    msg: "hahhahhaha lol 😂😂😂",
    time: "10:18 am",
    unreadMsgs: null,
  },
  {
    pp: userIcon,
    contact: "Boss",
    msg: "Meeting in 2 hours.",
    time: "10:02 am",
    unreadMsgs: null,
  },
  {
    pp: userIcon,
    contact: "Sarah",
    msg: "The test was sooo hard 😓",
    time: "9:47 am",
    unreadMsgs: 3,
  },
  {
    pp: userIcon,
    contact: "Doc 🏥",
    msg: "Hey doc, waitng for the results",
    time: "9:41 am",
    unreadMsgs: null,
  },
  {
    pp: userIcon,
    contact: "Best Friend",
    msg: "Wanna hang out? 🍺🍻",
    time: "yesterday",
    unreadMsgs: 3,
  },
  {
    pp: userIcon,
    contact: "Little Bro",
    msg: "I love this videogame 🕹🎮",
    time: "yesterday",
    unreadMsgs: 6,
  },
  {
    pp: userIcon,
    contact: "Professor Elizabeth",
    msg: "Forgot to send the task 😭",
    time: "yesterday",
    unreadMsgs: null,
  },
  {
    pp: userIcon,
    contact: "Test",
    msg: "Test chat ...",
    time: "yesterday",
    unreadMsgs: null,
  },
  {
    pp: userIcon,
    contact: "Test",
    msg: "Test chat ...",
    time: "yesterday",
    unreadMsgs: 7,
  },
  {
    pp: userIcon,
    contact: "Test",
    msg: "Test chat ...",
    time: "yesterday",
    unreadMsgs: null,
  },
  {
    pp: userIcon,
    contact: "Test",
    msg: "Test chat ...",
    time: "yesterday",
    unreadMsgs: 7,
  },
  {
    pp: userIcon,
    contact: "Test",
    msg: "Test chat ...",
    time: "yesterday",
    unreadMsgs: null,
  },
  {
    pp: userIcon,
    contact: "Test",
    msg: "Test chat ...",
    time: "yesterday",
    unreadMsgs: 7,
  },
  {
    pp: userIcon,
    contact: "Test",
    msg: "Test chat ...",
    time: "yesterday",
    unreadMsgs: null,
  },
  {
    pp: userIcon,
    contact: "Test",
    msg: "Test chat ...",
    time: "yesterday",
    unreadMsgs: 7,
  },
];

